# Generated by Django 3.0.3 on 2020-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('desc', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
