# Generated by Django 3.0.3 on 2020-02-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_socialconnect'),
    ]

    operations = [
        migrations.CreateModel(
            name='sidenavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_1', models.CharField(max_length=11)),
                ('row_2', models.CharField(max_length=11)),
                ('row_3', models.CharField(max_length=11)),
                ('row_4', models.CharField(max_length=11)),
                ('row_5', models.CharField(max_length=11)),
                ('row_6', models.CharField(max_length=11)),
            ],
        ),
    ]
