# Generated by Django 3.0.3 on 2020-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='pictures')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mobile1', models.CharField(max_length=15)),
                ('mobile2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('extra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='', verbose_name='pictures')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('extra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('one', models.CharField(max_length=100)),
                ('one_title', models.TextField()),
                ('two', models.CharField(max_length=100)),
                ('two_title', models.TextField()),
                ('three', models.CharField(max_length=100)),
                ('three_title', models.TextField()),
                ('four', models.CharField(max_length=100)),
                ('four_title', models.TextField()),
                ('five', models.CharField(max_length=100)),
                ('five_title', models.TextField()),
                ('six', models.CharField(max_length=100)),
                ('six_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
